/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.CarrerasDAO;
import datos.PostulanteDAO;
import entidades.Areas;
import entidades.Carreras;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Frecuencia 7
 */
public class DialogReportarPostulantePorAulaYCarrera extends javax.swing.JDialog {

    /**
     * Creates new form DialogReportarPostulantePorAulaYCarrera
     */
    PostulanteDAO ep = new PostulanteDAO();
    Carreras carrera;
    DefaultTableModel modelo = new DefaultTableModel();

    public DialogReportarPostulantePorAulaYCarrera() throws SQLException {
        super(FrmPrincipal.getInstancia(), true);
        initComponents();
        setLocationRelativeTo(null);
        this.cboCarrera.setModel(ep.ObtIdCarrera());
        cboAula.setEnabled(false);

        ep.mostrarPorUbicacionCar(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboCarrera = new javax.swing.JComboBox<>();
        btnBuscar = new rsbuttom.RSButtonMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cboAula = new javax.swing.JComboBox<>();
        btnSalir = new rsbuttom.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboCarrera.setBackground(new java.awt.Color(204, 255, 255));
        cboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCarrera.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCarreraItemStateChanged(evt);
            }
        });
        jPanel1.add(cboCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 163, 36));

        btnBuscar.setBackground(new java.awt.Color(255, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.setColorHover(new java.awt.Color(255, 102, 102));
        btnBuscar.setColorNormal(new java.awt.Color(255, 0, 0));
        btnBuscar.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 155, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(modelo);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, 710, 210));

        cboAula.setBackground(new java.awt.Color(153, 255, 255));
        cboAula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Aula" }));
        jPanel1.add(cboAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 163, 36));

        btnSalir.setText("Salir");
        btnSalir.setColorHover(new java.awt.Color(102, 102, 255));
        btnSalir.setColorNormal(new java.awt.Color(255, 0, 51));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 163, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 3, 24)); // NOI18N
        jLabel1.setText("BUSCAR POSTULANTES SEGÚN EL AULA EN DONDE RINDIERON UN EXAMEN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 750, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            if (cboAula.getSelectedIndex() == 0 || cboCarrera.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un elemento");
            } else {

                String nomCarrera = cboCarrera.getSelectedItem().toString();
                carrera = CarrerasDAO.getInstancia().buscarCarrerasPorNombre(nomCarrera);
                ep.mostraPostulantePorAC(cboAula.getSelectedItem().toString(), carrera.getCodigoCarrera(), modelo);
            }
        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cboCarreraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCarreraItemStateChanged
        try {
            cboAula.setEnabled(true);
            String nomCarrera = cboCarrera.getSelectedItem().toString();
            carrera = CarrerasDAO.getInstancia().buscarCarrerasPorNombre(nomCarrera);
            if (carrera != null) {
                Areas area = CarrerasDAO.getInstancia().buscarAreaDeUnaCarrera(carrera.getCodigoCarrera());
                if (area != null) {

                    this.cboAula.setModel(ep.ObtIdAulaPorArea(area.getIdArea()));
                }
            }
        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }
    }//GEN-LAST:event_cboCarreraItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnBuscar;
    private rsbuttom.RSButtonMetro btnSalir;
    private javax.swing.JComboBox<String> cboAula;
    private javax.swing.JComboBox<String> cboCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
