/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.AreasDAO;
import datos.Conexion;
import entidades.Areas;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class DialogBuscarAreas extends javax.swing.JDialog {

    DefaultTableModel modelo = new DefaultTableModel();
    Areas areasSelec = new Areas();
    AreasDAO ad = new AreasDAO();

    public DialogBuscarAreas() throws SQLException {
        super(FrmPrincipal.getInstancia(), true);
        initComponents();
        setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/img/log.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel3, "src/img/pdf.png");
        ad.mostrarAreas(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnTodo = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtCodig = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(198, 222, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 121, 97));

        btnSalir.setBackground(new java.awt.Color(255, 153, 153));
        btnSalir.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 87, 30));

        btnTodo.setBackground(new java.awt.Color(106, 240, 166));
        btnTodo.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btnTodo.setText("Todo");
        btnTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodoActionPerformed(evt);
            }
        });
        jPanel1.add(btnTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 73, 30));

        btnSeleccionar.setBackground(new java.awt.Color(106, 240, 166));
        btnSeleccionar.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 30));

        btnBuscar.setBackground(new java.awt.Color(106, 240, 166));
        btnBuscar.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, 30));

        txtCodig.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCodig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigActionPerformed(evt);
            }
        });
        txtCodig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodig, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 300, 29));

        Tabla.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        Tabla.setModel(modelo);
        jScrollPane1.setViewportView(Tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 690, 170));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Codigo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 80, 66));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int i = Tabla.getSelectedRow();
        if (i != -1) {
            areasSelec.setIdArea(modelo.getValueAt(i, 0).toString());
            areasSelec.setNombreArea(modelo.getValueAt(i, 1).toString());
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debes Seleccionar un elemento");
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtCodig.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese un ID ");
        } else {

            String idArea = txtCodig.getText();
            try {
                ad.mostraAreaPorCodigo(idArea, modelo);
            } catch (SQLException ex) {
                System.out.println("ERROR: " + ex.getMessage());;

            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodoActionPerformed
        try {
            ad.mostrarAreas(modelo);
        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());;
        }
    }//GEN-LAST:event_btnTodoActionPerformed

    private void txtCodigKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigKeyTyped
        if (txtCodig.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigKeyTyped

    private void txtCodigKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigKeyReleased
        String idArea = txtCodig.getText();
        try {
            ad.mostraAreaPorCodigo(idArea, modelo);
        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());;

        }
    }//GEN-LAST:event_txtCodigKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodig;
    // End of variables declaration//GEN-END:variables
}
