/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.RangoPreguntasDAO;
import entidades.RangoPreguntas;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruno
 */
public class DialogBuscarRangoPreguntas extends javax.swing.JDialog {

    
    DefaultTableModel modelo = new DefaultTableModel();
    RangoPreguntas rangoselec = new RangoPreguntas();
    RangoPreguntasDAO rangodao = new RangoPreguntasDAO();
    
    public DialogBuscarRangoPreguntas() {
        super(FrmPrincipal.getInstancia(), true);
        try {
            initComponents();
            setLocationRelativeTo(null);
            rangodao.mostrarRangoPreguntas(modelo);
        } catch (SQLException ex) {
            System.out.println("ERROR: "+ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        txtNombreRango = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(236, 243, 207));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Nombre Rango");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        btnSeleccionar.setBackground(new java.awt.Color(168, 192, 215));
        btnSeleccionar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        Tabla.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        Tabla.setModel(modelo);
        jScrollPane1.setViewportView(Tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 570, 275));

        txtNombreRango.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtNombreRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreRangoActionPerformed(evt);
            }
        });
        txtNombreRango.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreRangoKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombreRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 210, -1));

        btnBuscar.setBackground(new java.awt.Color(168, 192, 215));
        btnBuscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        btnTodos.setBackground(new java.awt.Color(168, 192, 215));
        btnTodos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnTodos.setText("Todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });
        jPanel1.add(btnTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 100, -1));

        btnCerrar.setBackground(new java.awt.Color(234, 107, 107));
        btnCerrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel3.setText("BUSCAR RANGO DE PREGUNTAS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int i = Tabla.getSelectedRow();
        if (i != -1) {
            rangoselec.setIdRangoPreguntas(modelo.getValueAt(i, 0).toString());
            rangoselec.setNombre(modelo.getValueAt(i, 1).toString());
            rangoselec.setPuntajeCorrecta(Double.parseDouble(modelo.getValueAt(i, 2).toString()));
            rangoselec.setPuntajeIncorrecta(Double.parseDouble(modelo.getValueAt(i, 2).toString()));
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debes Seleccionar un elemento");
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void txtNombreRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRangoActionPerformed

    }//GEN-LAST:event_txtNombreRangoActionPerformed

    private void txtNombreRangoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreRangoKeyReleased
        String nombreRango = txtNombreRango.getText();
        try {
            rangodao.mostrarRangoPreguntasPorNombre(modelo, nombreRango);
        } catch (SQLException ex) {
            System.out.println("ERROR: "+ex.getMessage());
        }
    }//GEN-LAST:event_txtNombreRangoKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String nombreRango = txtNombreRango.getText();
        try {
            rangodao.mostrarRangoPreguntasPorNombre(modelo, nombreRango);
        } catch (SQLException ex) {
            System.out.println("ERROR: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        try {
            rangodao.mostrarRangoPreguntas(modelo);
        } catch (SQLException ex) {
            System.out.println("ERROR: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogBuscarRangoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogBuscarRangoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogBuscarRangoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogBuscarRangoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogBuscarRangoPreguntas dialog = new DialogBuscarRangoPreguntas();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNombreRango;
    // End of variables declaration//GEN-END:variables
}
