/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.CarrerasDAO;
import datos.ClaveDAO;
import datos.ExamenDAO;
import datos.ModalidadDAO;
import datos.PostulanteDAO;
import datos.RangoPreguntasDAO;
import datos.RespuestaDAO;
import entidades.Carreras;
import entidades.Clave;
import entidades.Examen;
import entidades.Modalidad;
import entidades.Postulante;
import entidades.RangoPreguntas;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruno
 */
public class DialogRespuestasCorrectas extends javax.swing.JDialog {

    PostulanteDAO postulanteDAO = new PostulanteDAO();
    ExamenDAO examendao = new ExamenDAO();
    Examen examen;
    Postulante postulante;
    DefaultTableModel modelo = new DefaultTableModel();
    PostulanteDAO postulantedao = new PostulanteDAO();
    RespuestaDAO respuestadao = new RespuestaDAO();

    public DialogRespuestasCorrectas() {
        super(FrmPrincipal.getInstancia(), true);
        initComponents();
        setLocationRelativeTo(null);
        btnSeleccionar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboSemestre = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnLimpiarSeleccion = new javax.swing.JButton();
        txtDia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboCarrera = new javax.swing.JComboBox<>();
        cboModalidad = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdExamen = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtNombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 222, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        Tabla.setModel(modelo);
        jScrollPane1.setViewportView(Tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 620, 200));

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel3.setText("RESPUESTAS CORRECTAS DE UN POSTULANTE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(217, 222, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "SELECCIONAR EXAMEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Semestre");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        cboSemestre.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        cboSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "2021-I", "2021-II" }));
        cboSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSemestreActionPerformed(evt);
            }
        });
        jPanel2.add(cboSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 240, 30));

        btnBuscar.setBackground(new java.awt.Color(168, 192, 215));
        btnBuscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        btnLimpiarSeleccion.setBackground(new java.awt.Color(234, 107, 107));
        btnLimpiarSeleccion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnLimpiarSeleccion.setText("Restaurar");
        btnLimpiarSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarSeleccionActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiarSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 120, -1));

        txtDia.setEditable(false);
        txtDia.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaKeyTyped(evt);
            }
        });
        jPanel2.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 70, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("Día");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 20));

        txtMes.setEditable(false);
        txtMes.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesKeyTyped(evt);
            }
        });
        jPanel2.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 70, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setText("Mes");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, 20));

        txtAño.setEditable(false);
        txtAño.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAñoKeyTyped(evt);
            }
        });
        jPanel2.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 70, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setText("Año");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, 20));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("Carrera");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        cboCarrera.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        cboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Biologia", "Biologia Pesquera", "Microbiologia y Parasitologia", "Farmacia y Bioquimica", "Ingenieria Quimica", "Ingenieria Ambiental", "Educacion Inicial", "Educacion Primaria", "Educacion Secundaria", "Ciencias De La Comunicacion", "Medicina", "Estomatologia", "Enfermeria", "Antropologia", "Arqueologia", "Trabajo Social", "Turismo", "Historia", "Arquitectura y Urbanismo", "Estadistica", "Matematica", "Fisica", "Ingenieria Informatica", "Administracion", "Contabilidad", "Economia", "Derecho", "Ciencias Politcas y Gobernabilidad", "Ingenieria Industrial", "Ingenieria Mecanica", "Ingenieria Metalurgica", "Ingenieria Materiales", "Ingenieria Sistemas", "Ingenieria Minas", "Ingenieria Mecatronica", "Ingenieria Civil", "Ingenieria Agroindustrial", "Ingenieria Agricola", "Ingenieria Agronoma", "Ingenieria Zootecnia" }));
        cboCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCarreraActionPerformed(evt);
            }
        });
        jPanel2.add(cboCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 240, 30));

        cboModalidad.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        cboModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "ORDINARIO", "EXCELENCIA", "DISCAPACITADOS", "CEPUNT" }));
        cboModalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboModalidadActionPerformed(evt);
            }
        });
        jPanel2.add(cboModalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 240, 30));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("Id Examen");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setText("Modalidad");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txtIdExamen.setEditable(false);
        txtIdExamen.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jPanel2.add(txtIdExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 210, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 520, 440));

        jPanel3.setBackground(new java.awt.Color(217, 222, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "SELECCCIONAR POSTULANTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 18))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombres.setEditable(false);
        txtNombres.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        jPanel3.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 390, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("Nombres");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 20));

        txtDni.setEditable(false);
        txtDni.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });
        jPanel3.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 170, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setText("DNI");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 20));

        btnSeleccionar.setBackground(new java.awt.Color(153, 255, 153));
        btnSeleccionar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel3.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 150, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 620, 190));

        btnMostrar.setBackground(new java.awt.Color(126, 195, 224));
        btnMostrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnMostrar.setText("Mostrar Respuestas Correctas");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 290, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSemestreActionPerformed

    }//GEN-LAST:event_cboSemestreActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            String semestre = cboSemestre.getSelectedItem().toString();
            String nomCarrera = cboCarrera.getSelectedItem().toString();
            Carreras carrera = CarrerasDAO.getInstancia().buscarCarrerasPorNombre(nomCarrera);

            System.out.println("Carrera" + carrera.getCodigoCarrera());

            String nomModalidad = cboModalidad.getSelectedItem().toString();

            Modalidad modalidad = ModalidadDAO.getInstancia().buscarModalidadPorNombre(nomModalidad);

            System.out.println("Modalidad: " + modalidad.getIdModalidad());

            examen = examendao.buscarExamen(semestre, carrera.getCodigoCarrera(), modalidad.getIdModalidad());

            System.out.println("Examen: " + examen.getIdExamen());

            txtIdExamen.setText(examen.getIdExamen());
            txtDia.setText(String.valueOf(examen.getFecha().getDia()));
            txtMes.setText(String.valueOf(examen.getFecha().getMes()));
            txtAño.setText(String.valueOf(examen.getFecha().getAño()));
            examendao.setOrdenDeMerito(examen, carrera.getCodigoCarrera());
            btnSeleccionar.setEnabled(true);

        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        } catch (Exception e) {
            System.out.println("ERROR: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarSeleccionActionPerformed

        txtDia.setText("");
        txtMes.setText("");
        txtAño.setText("");
        txtIdExamen.setText("");
        cboSemestre.setSelectedIndex(0);
        cboModalidad.setSelectedIndex(0);
        cboCarrera.setSelectedIndex(0);
        txtNombres.setText("");
        txtDni.setText("");
        cboSemestre.requestFocus();
        btnMostrar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarSeleccionActionPerformed

    private void txtDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaKeyTyped

    private void txtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesKeyTyped

    private void txtAñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoKeyTyped

    private void cboCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCarreraActionPerformed

    private void cboModalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboModalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboModalidadActionPerformed

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        if (txtNombres.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniKeyTyped

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        try {
            String nomCarrera = cboCarrera.getSelectedItem().toString();
            Carreras carrera = CarrerasDAO.getInstancia().buscarCarrerasPorNombre(nomCarrera);
            DialogBuscarPostulanteTabla f = new DialogBuscarPostulanteTabla(examen.getIdExamen(), carrera.getCodigoCarrera());
            f.setVisible(true);
            postulante = f.postulanteSelec;
            String nombres = postulante.getApellido_paterno() + " " + postulante.getApellido_materno() + ", " + postulante.getNombres();
            txtNombres.setText(nombres);
            txtDni.setText(postulante.getDni());
        } catch (SQLException ex) {
            System.out.println("ERROR: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        if (postulante != null && examen != null) {
            try {
                respuestadao.mostrarRespuestasCorrectasDePostulanteEnUnExamen(modelo, postulante.getIdPostulante(), examen.getIdExamen());
            } catch (SQLException ex) {
                System.out.println("Error: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogRespuestasCorrectas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogRespuestasCorrectas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogRespuestasCorrectas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogRespuestasCorrectas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogRespuestasCorrectas dialog = new DialogRespuestasCorrectas();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiarSeleccion;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> cboCarrera;
    private javax.swing.JComboBox<String> cboModalidad;
    private javax.swing.JComboBox<String> cboSemestre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtIdExamen;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
