/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.ClaveDAO;
import datos.ExamenDAO;
import datos.RangoPreguntasDAO;
import entidades.Examen;
import entidades.composite2.RangoPreguntasComposite;
import entidades.composite2.RangoPreguntas;
import entidades.composite2.RangoPreguntasLeaf;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruno
 */
public class DialogRangoPreguntas extends javax.swing.JDialog {

    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel claves = new DefaultTableModel();
    RangoPreguntasLeaf clave;
    RangoPreguntasComposite rango;
    RangoPreguntasDAO rangodao = new RangoPreguntasDAO();
    ClaveDAO claveDAO = new ClaveDAO();

    public DialogRangoPreguntas() {
        super(FrmPrincipal.getInstancia(), true);
        initComponents();
        desHabilitar();
        setLocationRelativeTo(null);
        try {
            rangodao.mostrarRangoPreguntas(modelo);
        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }
    }

    public void habilitar() {
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnConsultar.setEnabled(false);
    }

    public void desHabilitar() {
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnConsultar.setEnabled(true);
    }

    public void limpiarEntradas() {
        txtIdRango.setText("");
        txtNombre.setText("");

        txtIdClave.setText("");
        txtNumero.setText("");
        txtLetra.setText("");
        txtIdExamen.setText("");

        txtIdRango.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnBuscarClave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIdClave = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLetra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIdExamen = new javax.swing.JTextField();
        btnAgregarClave = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtIdRango = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIncorrecta = new javax.swing.JTextField();
        txtCorrecta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(154, 200, 203));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel3.setText("RANGO PREGUNTAS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        Tabla.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        Tabla.setModel(claves);
        Tabla.setGridColor(new java.awt.Color(154, 200, 203));
        jScrollPane1.setViewportView(Tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, 440, 220));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("Nombre");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("ID Rango Preguntas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 20));

        txtNombre.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 270, -1));

        btnGuardar.setBackground(new java.awt.Color(168, 192, 215));
        btnGuardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, 120, -1));

        btnConsultar.setBackground(new java.awt.Color(168, 192, 215));
        btnConsultar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, 130, -1));

        btnActualizar.setBackground(new java.awt.Color(168, 192, 215));
        btnActualizar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 590, 140, -1));

        btnEliminar.setBackground(new java.awt.Color(234, 107, 107));
        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 640, 140, -1));

        btnRestaurar.setBackground(new java.awt.Color(234, 107, 107));
        btnRestaurar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 640, 140, -1));

        btnSalir.setBackground(new java.awt.Color(234, 107, 107));
        btnSalir.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, 90, -1));

        jPanel2.setBackground(new java.awt.Color(154, 200, 203));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLAVE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarClave.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnBuscarClave.setText("...");
        btnBuscarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("ID Clave");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        txtIdClave.setEditable(false);
        txtIdClave.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtIdClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdClaveKeyTyped(evt);
            }
        });
        jPanel2.add(txtIdClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 230, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Numero");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtNumero.setEditable(false);
        txtNumero.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 230, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("Letra");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtLetra.setEditable(false);
        txtLetra.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLetraKeyTyped(evt);
            }
        });
        jPanel2.add(txtLetra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 230, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("ID Examen");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        txtIdExamen.setEditable(false);
        txtIdExamen.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtIdExamen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdExamenKeyTyped(evt);
            }
        });
        jPanel2.add(txtIdExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 230, -1));

        btnAgregarClave.setBackground(new java.awt.Color(168, 192, 215));
        btnAgregarClave.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnAgregarClave.setText("Agregar");
        btnAgregarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        btnEliminar1.setBackground(new java.awt.Color(234, 107, 107));
        btnEliminar1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(234, 107, 107));
        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 430, 340));

        txtIdRango.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtIdRango.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdRangoKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 140, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("Puntaje Incorrecta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 20));

        txtIncorrecta.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtIncorrecta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIncorrectaKeyTyped(evt);
            }
        });
        jPanel1.add(txtIncorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 150, -1));

        txtCorrecta.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtCorrecta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorrectaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 140, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setText("Puntaje Correcta");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 20));

        jTable2.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jTable2.setModel(modelo);
        jTable2.setGridColor(new java.awt.Color(154, 200, 203));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 480, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorrectaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorrectaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorrectaKeyTyped

    private void txtIncorrectaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIncorrectaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIncorrectaKeyTyped

    private void txtIdRangoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdRangoKeyTyped
        if (txtIdRango.getText().length() >= 25) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdRangoKeyTyped

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        // TODO add your handling code here:
        limpiarEntradas();
        desHabilitar();
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String id = txtIdRango.getText();
        if (!id.equals("")) {
            try {
                rangodao.eliminar(id);
                JOptionPane.showMessageDialog(this, "Se eliminó el registro");
                rangodao.mostrarRangoPreguntas(modelo);
                limpiarEntradas();
                desHabilitar();
            } catch (SQLException ex) {
                System.out.println("ERROR: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Este id no existe");

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    if (txtNombre.getText().equals("")
            || txtIdRango.getText().equals("")
            || txtIdClave.getText().equals("")
            || txtNumero.getText().equals("")
            || txtLetra.getText().equals("")
            || txtIdExamen.getText().equals("")
            || txtCorrecta.getText().equals("")
            || txtIncorrecta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No deje el campo vacio");
        } else {

            try {
                String idRango = txtIdRango.getText();
                String nombre = txtNombre.getText();
                double correcta = Double.parseDouble(txtCorrecta.getText());
                double incorrecta = Double.parseDouble(txtIncorrecta.getText());
                rango = new RangoPreguntasComposite(idRango, nombre, correcta, incorrecta);
                
                rangodao.actualizar(rango);
                limpiarEntradas();
                desHabilitar();
                rangodao.mostrarRangoPreguntas(modelo);
            } catch (SQLException ex) {
                System.out.println("ERROR: " + ex.getMessage());

            }

        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        String idRango = txtIdRango.getText();
        if (idRango.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "POR FAVOR INGRESA EL ID DEL RANGO");
        } else {
            try {
                RangoPreguntasComposite x;
                x = rangodao.buscarRango(idRango);
                if (x != null) {
                    txtNombre.setText(x.getNombre());
                    txtCorrecta.setText(String.valueOf(x.getPuntajeCorrecta()));
                    txtIncorrecta.setText(String.valueOf(x.getPuntajeIncorrecta()));
                    txtNombre.setText(x.getNombre());

                    habilitar();
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontró dicho rango");
                }
            } catch (SQLException ex) {
                System.out.println("ERROR: " + ex.getMessage());

            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtNombre.getText().equals("")
            || txtIdRango.getText().equals("")
            || txtIdClave.getText().equals("")
            || txtNumero.getText().equals("")
            || txtLetra.getText().equals("")
            || txtIdExamen.getText().equals("")
            || txtCorrecta.getText().equals("")
            || txtIncorrecta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No deje el campo vacio");
        } else {

            try {
                String idRango = txtIdRango.getText();
                String nombre = txtNombre.getText();
                double correcta = Double.parseDouble(txtCorrecta.getText());
                double incorrecta = Double.parseDouble(txtIncorrecta.getText());
                rango = new RangoPreguntasComposite(idRango, nombre, correcta, incorrecta);
                
                rangodao.insertar(rango);
                limpiarEntradas();
                rangodao.mostrarRangoPreguntas(modelo);
            } catch (SQLException ex) {
                System.out.println("ERROR: " + ex.getMessage());

            }

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if (txtIdExamen.getText().length() >= 60) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtIdExamenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdExamenKeyTyped
        if (txtIdExamen.getText().length() >= 25) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdExamenKeyTyped

    private void txtLetraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLetraKeyTyped
        char c = evt.getKeyChar();
        if (txtLetra.getText().length() >= 13 || (c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtLetraKeyTyped

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        if (txtNumero.getText().length() >= 25) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void txtIdClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdClaveKeyTyped
        if (txtIdClave.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdClaveKeyTyped

    private void btnBuscarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClaveActionPerformed
        // TODO add your handling code here:
        DialogBuscarClave f = new DialogBuscarClave();
        f.setVisible(true);
        clave = f.claveSelec;
        txtIdClave.setText(clave.getIdClave());
        txtNumero.setText(String.valueOf(clave.getNumero()));
        txtLetra.setText(String.valueOf(clave.getLetra()));
        txtIdExamen.setText(clave.getExamen().getIdExamen());
    }//GEN-LAST:event_btnBuscarClaveActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        /*
        int i = Tabla.getSelectedRow();
        if (i != -1) {
            int rpta = JOptionPane.showConfirmDialog(null, "Esta seguro?", "Eliminar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (rpta == JOptionPane.OK_OPTION) {
                String idEjemplar = modelo.getValueAt(i, 0).toString();
                try {
                    usuario = usuariodao.buscarUsuario(txtIdUsuario.getText());
                    usuario.setEjemplares(ejemplares);
                    System.out.println("tamaño de ejemplares al querer borrar: " + ejemplares.size());
                    System.out.println("EL i es " + i);
                    System.out.println("usuario.getEjemplares().size()" + usuario.getEjemplares().size());
                    dp = usuario.getEjemplares().get(i);
                    System.out.println("dp = usuario.getEjemplares().get(i); ->" + usuario.getEjemplares().get(i).getEjemplar().getIdEjemplar());
                    ejemplares.remove(i);
                    //autores.re
                    usuariodao.eliminarEjemplar(idEjemplar);
                    System.out.println("Al eliminar tiene " + ejemplares.size());
                } catch (SQLException ex) {
                    System.out.println("ERROR: " + ex.getMessage());
                }
                modelo.removeRow(i);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un ejemplar", "Eliminar", 1);
        }*/
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtIdClave.setText("");
        txtNumero.setText("");
        txtLetra.setText("");
        txtIdExamen.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClaveActionPerformed

        // TODO add your handling code here:
        if (txtIdClave.getText().equals("")
            || txtNumero.getText().equals("")
            || txtLetra.getText().equals("") || txtIdExamen.getText().equals("")                ) {
            JOptionPane.showMessageDialog(null, "NO DEJE EL CAMPO VACIO");

        } else {
            Object [] fila = {clave.getIdClave(), clave.getNumero(), clave.getLetra(), clave.getExamen().getIdExamen()};
            claves.addRow(fila);
            //rango;
            RangoPreguntasComposite r = new RangoPreguntasComposite("", "", 0, 0);
            

        }
    }//GEN-LAST:event_btnAgregarClaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogRangoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogRangoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogRangoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogRangoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogRangoPreguntas dialog = new DialogRangoPreguntas();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarClave;
    private javax.swing.JButton btnBuscarClave;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCorrecta;
    private javax.swing.JTextField txtIdClave;
    private javax.swing.JTextField txtIdExamen;
    private javax.swing.JTextField txtIdRango;
    private javax.swing.JTextField txtIncorrecta;
    private javax.swing.JTextField txtLetra;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
