/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.builder.CepuntModalidadBuilder;
import entidades.builder.DireccionSistemas;
import entidades.builder.DiscapacitadosModalidadBuilder;
import entidades.builder.ExcelenciaModalidadBuilder;
import entidades.builder.OrdinarioModalidadBuilder;
import datos.ModalidadDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class FrmPrincipal extends javax.swing.JFrame {

    private static FrmPrincipal instancia;
    ModalidadDAO md = new ModalidadDAO();

    public static FrmPrincipal getInstancia() {
        if (instancia == null) {
            instancia = new FrmPrincipal();
        }
        return instancia;
    }

    public FrmPrincipal() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/img/unt-reescalado.png");
        this.setLocationRelativeTo(null);

    }

    public void modalidad1() throws SQLException {
        DireccionSistemas x = new DireccionSistemas();
        x.setBuilder(new OrdinarioModalidadBuilder());
        x.construirModalidad();
        md.insertar(x);
    }

    public void modalidad2() throws SQLException {
        DireccionSistemas x = new DireccionSistemas();
        x.setBuilder(new ExcelenciaModalidadBuilder());
        x.construirModalidad();
        md.insertar(x);
    }

    public void modalidad4() throws SQLException {
        DireccionSistemas x = new DireccionSistemas();
        x.setBuilder(new CepuntModalidadBuilder());
        x.construirModalidad();
        md.insertar(x);
    }
      public void modalidad3() throws SQLException {
        DireccionSistemas x = new DireccionSistemas();
        x.setBuilder(new DiscapacitadosModalidadBuilder());
        x.construirModalidad();
        md.insertar(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAreas = new javax.swing.JMenu();
        mnuiRegistrarAreas = new javax.swing.JMenuItem();
        mnuiReporteAreas = new javax.swing.JMenuItem();
        mnuFacultad = new javax.swing.JMenu();
        mnuiRegistrarFacultad = new javax.swing.JMenuItem();
        mnuiReporteFacultad = new javax.swing.JMenuItem();
        mnuCarreras = new javax.swing.JMenu();
        mnuiRegistrarCarreras = new javax.swing.JMenuItem();
        mnuiReporteCarreras = new javax.swing.JMenuItem();
        mnuModalidad = new javax.swing.JMenu();
        mnuiRegistrarModalidad = new javax.swing.JMenuItem();
        mnuiReporteModalidades = new javax.swing.JMenuItem();
        mnuAula = new javax.swing.JMenu();
        mnuiRegistrarAula = new javax.swing.JMenuItem();
        mnuiReporteAulas = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mnuAreas.setText("AREAS");

        mnuiRegistrarAreas.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mnuiRegistrarAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save_48px.png"))); // NOI18N
        mnuiRegistrarAreas.setText("Registrar Areas");
        mnuiRegistrarAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiRegistrarAreasActionPerformed(evt);
            }
        });
        mnuAreas.add(mnuiRegistrarAreas);

        mnuiReporteAreas.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mnuiReporteAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit Property_48px.png"))); // NOI18N
        mnuiReporteAreas.setText("Reporte Areas");
        mnuiReporteAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiReporteAreasActionPerformed(evt);
            }
        });
        mnuAreas.add(mnuiReporteAreas);

        jMenuBar1.add(mnuAreas);

        mnuFacultad.setText("FACULTAD");

        mnuiRegistrarFacultad.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mnuiRegistrarFacultad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save_48px.png"))); // NOI18N
        mnuiRegistrarFacultad.setText("Registrar Facultad");
        mnuiRegistrarFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiRegistrarFacultadActionPerformed(evt);
            }
        });
        mnuFacultad.add(mnuiRegistrarFacultad);

        mnuiReporteFacultad.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mnuiReporteFacultad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit Property_48px.png"))); // NOI18N
        mnuiReporteFacultad.setText("Reporte Facultad");
        mnuiReporteFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiReporteFacultadActionPerformed(evt);
            }
        });
        mnuFacultad.add(mnuiReporteFacultad);

        jMenuBar1.add(mnuFacultad);

        mnuCarreras.setText("CARRERAS");

        mnuiRegistrarCarreras.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mnuiRegistrarCarreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save_48px.png"))); // NOI18N
        mnuiRegistrarCarreras.setText("Registrar Carreras");
        mnuiRegistrarCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiRegistrarCarrerasActionPerformed(evt);
            }
        });
        mnuCarreras.add(mnuiRegistrarCarreras);

        mnuiReporteCarreras.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mnuiReporteCarreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit Property_48px.png"))); // NOI18N
        mnuiReporteCarreras.setText("Reporte Carreras");
        mnuiReporteCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiReporteCarrerasActionPerformed(evt);
            }
        });
        mnuCarreras.add(mnuiReporteCarreras);

        jMenuBar1.add(mnuCarreras);

        mnuModalidad.setText("MODALIDAD");

        mnuiRegistrarModalidad.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mnuiRegistrarModalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save_48px.png"))); // NOI18N
        mnuiRegistrarModalidad.setText("Registrar Modalidad ");
        mnuiRegistrarModalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiRegistrarModalidadActionPerformed(evt);
            }
        });
        mnuModalidad.add(mnuiRegistrarModalidad);

        mnuiReporteModalidades.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mnuiReporteModalidades.setText("Reporte de Modalidades");
        mnuiReporteModalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiReporteModalidadesActionPerformed(evt);
            }
        });
        mnuModalidad.add(mnuiReporteModalidades);

        jMenuBar1.add(mnuModalidad);

        mnuAula.setText("AULA");

        mnuiRegistrarAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save_48px.png"))); // NOI18N
        mnuiRegistrarAula.setText("Registrar Aula");
        mnuiRegistrarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiRegistrarAulaActionPerformed(evt);
            }
        });
        mnuAula.add(mnuiRegistrarAula);

        mnuiReporteAulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit Property_48px.png"))); // NOI18N
        mnuiReporteAulas.setText("Reporte Aulas");
        mnuiReporteAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiReporteAulasActionPerformed(evt);
            }
        });
        mnuAula.add(mnuiReporteAulas);

        jMenuBar1.add(mnuAula);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiRegistrarAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiRegistrarAreasActionPerformed
        try {
            DialogAreas f = new DialogAreas();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuiRegistrarAreasActionPerformed

    private void mnuiRegistrarFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiRegistrarFacultadActionPerformed
        try {
            DialogFacultad f = new DialogFacultad();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuiRegistrarFacultadActionPerformed

    private void mnuiRegistrarCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiRegistrarCarrerasActionPerformed
        try {
            DialogCarreras f = new DialogCarreras();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuiRegistrarCarrerasActionPerformed

    private void mnuiReporteAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiReporteAreasActionPerformed
        try {
            DialogBuscarAreas f = new DialogBuscarAreas();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuiReporteAreasActionPerformed

    private void mnuiReporteFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiReporteFacultadActionPerformed
        try {
            DialogBuscarFacultad f = new DialogBuscarFacultad();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuiReporteFacultadActionPerformed

    private void mnuiReporteCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiReporteCarrerasActionPerformed
        try {
            DialogReporteCarreras f = new DialogReporteCarreras();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuiReporteCarrerasActionPerformed

    private void mnuiRegistrarModalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiRegistrarModalidadActionPerformed

        try {
            modalidad1();
            modalidad2();
            modalidad4();
            modalidad3();
            DialogModalidad f = new DialogModalidad();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_mnuiRegistrarModalidadActionPerformed

    private void mnuiRegistrarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiRegistrarAulaActionPerformed
        try {
            DialogAula f = new DialogAula();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuiRegistrarAulaActionPerformed

    private void mnuiReporteAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiReporteAulasActionPerformed
        try {
            DialogBuscarAula f = new DialogBuscarAula();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuiReporteAulasActionPerformed

    private void mnuiReporteModalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiReporteModalidadesActionPerformed
        try {
            DialogBuscarModalidad f = new DialogBuscarModalidad();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuiReporteModalidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuAreas;
    private javax.swing.JMenu mnuAula;
    private javax.swing.JMenu mnuCarreras;
    private javax.swing.JMenu mnuFacultad;
    private javax.swing.JMenu mnuModalidad;
    private javax.swing.JMenuItem mnuiRegistrarAreas;
    private javax.swing.JMenuItem mnuiRegistrarAula;
    private javax.swing.JMenuItem mnuiRegistrarCarreras;
    private javax.swing.JMenuItem mnuiRegistrarFacultad;
    private javax.swing.JMenuItem mnuiRegistrarModalidad;
    private javax.swing.JMenuItem mnuiReporteAreas;
    private javax.swing.JMenuItem mnuiReporteAulas;
    private javax.swing.JMenuItem mnuiReporteCarreras;
    private javax.swing.JMenuItem mnuiReporteFacultad;
    private javax.swing.JMenuItem mnuiReporteModalidades;
    // End of variables declaration//GEN-END:variables
}
