/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.paneles;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import presentacion.DialogReportePorCarrera;
import presentacion.DialogReporteRevision;
import presentacion.DialogRevisarExamen;

/**
 *
 * @author Frecuencia 7
 */
public class pnlReporteResultados extends javax.swing.JPanel {

    public pnlReporteResultados() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPorCarrera = new rsbuttom.RSButtonMetro();
        btnModalidad = new rsbuttom.RSButtonMetro();
        btnPorArea = new rsbuttom.RSButtonMetro();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 39)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTE RESULTADOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 499, -1));

        btnPorCarrera.setBackground(new java.awt.Color(255, 153, 102));
        btnPorCarrera.setText("POR CARRERA");
        btnPorCarrera.setColorHover(new java.awt.Color(255, 51, 51));
        btnPorCarrera.setColorNormal(new java.awt.Color(255, 153, 102));
        btnPorCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorCarreraActionPerformed(evt);
            }
        });

        btnModalidad.setBackground(new java.awt.Color(255, 153, 102));
        btnModalidad.setText("POR MODALIDAD");
        btnModalidad.setColorHover(new java.awt.Color(255, 51, 51));
        btnModalidad.setColorNormal(new java.awt.Color(255, 153, 102));
        btnModalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModalidadActionPerformed(evt);
            }
        });

        btnPorArea.setBackground(new java.awt.Color(255, 153, 102));
        btnPorArea.setText("POR AREA");
        btnPorArea.setColorHover(new java.awt.Color(255, 51, 51));
        btnPorArea.setColorNormal(new java.awt.Color(255, 153, 102));
        btnPorArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPorArea, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPorCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPorCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnPorArea, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 520, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf-file.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 650, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPorCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorCarreraActionPerformed
        try {
            DialogReportePorCarrera f;
            f = new DialogReportePorCarrera();
            f.setVisible(true);
        } catch (SQLException ex) {
            System.out.println("ERROR: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnPorCarreraActionPerformed

    private void btnModalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModalidadActionPerformed

    }//GEN-LAST:event_btnModalidadActionPerformed

    private void btnPorAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPorAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnModalidad;
    private rsbuttom.RSButtonMetro btnPorArea;
    private rsbuttom.RSButtonMetro btnPorCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
